name: coverageReport

on: pull_request

jobs:
  report-code-coverage:
    name: Report code coverage
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: write
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install Deps"
        run: npm install
      - name: "🧪 test code"
        run: npm run test:coverage
      - name: "📋 Report Coverage"
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
